name: Installation test

on: [workflow_dispatch]

jobs:
  install:
    name: Test installation on Ubuntu 22.04LTS
    runs-on: ubuntu-22.04

    steps:
      - run: df -h
      - run: |
              sudo rm -rf /usr/local/lib/android
              df -h
      - run: |
              sudo rm -rf /usr/share/dotnet
              df -h
      - run: |
              sudo rm -rf /opt/ghc
              df -h
      - run: |
              sudo rm -rf /opt/hostedtoolcache/CodeQL
              df -h
      - run: |
              sudo docker image prune --all --force
              df -h
      - run: |
              sudo apt-get purge -y \
                '^llvm-.*' \
                'php.*' \
                '^mongodb-.*' \
                '^mysql-.*' \
                azure-cli \
                google-cloud-cli \
                google-chrome-stable \
                firefox \
                powershell \
                microsoft-edge-stable \
                mono-devel
              sudo apt-get autoremove -y
              sudo apt-get clean
              df -h
      #- uses: actions/checkout@v4
      #- name: install
      #  run: sudo ./bin/wally-tool-chain-install.sh
    
