name: Installation
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  ubuntu_install:
    name: Test installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Free up storage
        run: |
              df -h
              ./.github/cli-space-cleanup.sh
              df -h
      - name: install
        run: sudo ./bin/wally-tool-chain-install.sh --clean
      - name: make tests
        run: |
              source setup.sh
              make riscof
      - name: regresssion
        run: |
              source setup.sh
              lint-wally
              wsim --sim verilator  rv32e arch32e
              wsim --sim verilator  rv32i arch32i
              wsim --sim verilator  rv32imc arch32i
              wsim --sim verilator  rv32imc arch32c
              wsim --sim verilator  rv32imc arch32m
              wsim --sim verilator  rv32imc wally32periph
              wsim --sim verilator  rv32gc arch32f
              wsim --sim verilator  rv32gc arch32d
              wsim --sim verilator  rv32gc arch32f_fma
              wsim --sim verilator  rv32gc arch32d_fma
              wsim --sim verilator  rv32gc arch32f_divsqrt
              wsim --sim verilator  rv32gc arch32d_divsqrt
              wsim --sim verilator  rv32gc arch32i
              wsim --sim verilator  rv32gc arch32priv
              wsim --sim verilator  rv32gc arch32c
              wsim --sim verilator  rv32gc arch32m
              wsim --sim verilator  rv32gc arch32a_amo
              wsim --sim verilator  rv32gc arch32zifencei
              wsim --sim verilator  rv32gc arch32zicond
              wsim --sim verilator  rv32gc arch32zba
              wsim --sim verilator  rv32gc arch32zbb
              wsim --sim verilator  rv32gc arch32zbc
              wsim --sim verilator  rv32gc arch32zbs
              wsim --sim verilator  rv32gc arch32zfh
              wsim --sim verilator  rv32gc arch32zfh_fma
              wsim --sim verilator  rv32gc arch32zfh_divsqrt
              wsim --sim verilator  rv32gc arch32zfaf
              wsim --sim verilator  rv32gc arch32zfad
              wsim --sim verilator  rv32gc wally32a_lrsc
              wsim --sim verilator  rv32gc wally32priv
              wsim --sim verilator  rv32gc wally32periph
              wsim --sim verilator  rv32gc arch32zcb
              wsim --sim verilator  rv32gc arch32zbkb
              wsim --sim verilator  rv32gc arch32zbkc
              wsim --sim verilator  rv32gc arch32zbkx
              wsim --sim verilator  rv32gc arch32zknd
              wsim --sim verilator  rv32gc arch32zkne
              wsim --sim verilator  rv32gc arch32zknh
              wsim --sim verilator  rv64i arch64i
              wsim --sim verilator  rv64gc coverage64gc
              wsim --sim verilator  rv64gc arch64i
              wsim --sim verilator  rv64gc arch64priv
              wsim --sim verilator  rv64gc arch64c
              wsim --sim verilator  rv64gc arch64m
              wsim --sim verilator  rv64gc arch64zcb
              wsim --sim verilator  rv64gc arch64zifencei
              wsim --sim verilator  rv64gc arch64zicond
              wsim --sim verilator  rv64gc arch64a_amo
              wsim --sim verilator  rv64gc wally64a_lrsc
              wsim --sim verilator  rv64gc wally64periph
              wsim --sim verilator  rv64gc wally64priv
              wsim --sim verilator  rv64gc arch64zbkb
              wsim --sim verilator  rv64gc arch64zbkc
              wsim --sim verilator  rv64gc arch64zbkx
              wsim --sim verilator  rv64gc arch64zknd
              wsim --sim verilator  rv64gc arch64zkne
              wsim --sim verilator  rv64gc arch64zknh
              wsim --sim verilator  rv64gc arch64zba
              wsim --sim verilator  rv64gc arch64zbb
              wsim --sim verilator  rv64gc arch64zbc
              wsim --sim verilator  rv64gc arch64zbs
              wsim --sim verilator  rv64gc arch64f
              wsim --sim verilator  rv64gc arch64d
              wsim --sim verilator  rv64gc arch64zfh
              wsim --sim verilator  rv64gc arch64f_fma
              wsim --sim verilator  rv64gc arch64d_fma
              wsim --sim verilator  rv64gc arch64zfh_fma
              wsim --sim verilator  rv64gc arch64f_divsqrt
              wsim --sim verilator  rv64gc arch64d_divsqrt
              wsim --sim verilator  rv64gc arch64zfh_divsqrt
              wsim --sim verilator  rv64gc arch64zfaf
              wsim --sim verilator  rv64gc arch64zfad

  rhel_family_install:
    name: Test installation on ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
      options: --privileged --mount type=bind,source=/,target=/host --pid=host --entrypoint /bin/bash
    strategy:
      fail-fast: false
      matrix:
        os: ["rockylinux:8", "rockylinux:9", "almalinux:8", "almalinux:9"]
    steps:
      - name: Install dependencies
        run: |
              dnf install -y sudo git
              dnf install curl -y --allowerasing || true
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Fix git ownership
        run: git config --global --add safe.directory '*'
      - name: Free up storage
        run: |
              df -h
              nsenter -t 1 -m -u -n -i bash -c "$(cat .github/cli-space-cleanup.sh)"
              df -h
      - name: install
        run: ./bin/wally-tool-chain-install.sh --clean
      - name: make tests
        run: |
              source setup.sh
              make riscof
      - name: regresssion
        run: |
              source setup.sh
              lint-wally
              wsim --sim verilator  rv32e arch32e
              wsim --sim verilator  rv32i arch32i
              wsim --sim verilator  rv32imc arch32i
              wsim --sim verilator  rv32imc arch32c
              wsim --sim verilator  rv32imc arch32m
              wsim --sim verilator  rv32imc wally32periph
              wsim --sim verilator  rv32gc arch32f
              wsim --sim verilator  rv32gc arch32d
              wsim --sim verilator  rv32gc arch32f_fma
              wsim --sim verilator  rv32gc arch32d_fma
              wsim --sim verilator  rv32gc arch32f_divsqrt
              wsim --sim verilator  rv32gc arch32d_divsqrt
              wsim --sim verilator  rv32gc arch32i
              wsim --sim verilator  rv32gc arch32priv
              wsim --sim verilator  rv32gc arch32c
              wsim --sim verilator  rv32gc arch32m
              wsim --sim verilator  rv32gc arch32a_amo
              wsim --sim verilator  rv32gc arch32zifencei
              wsim --sim verilator  rv32gc arch32zicond
              wsim --sim verilator  rv32gc arch32zba
              wsim --sim verilator  rv32gc arch32zbb
              wsim --sim verilator  rv32gc arch32zbc
              wsim --sim verilator  rv32gc arch32zbs
              wsim --sim verilator  rv32gc arch32zfh
              wsim --sim verilator  rv32gc arch32zfh_fma
              wsim --sim verilator  rv32gc arch32zfh_divsqrt
              wsim --sim verilator  rv32gc arch32zfaf
              wsim --sim verilator  rv32gc arch32zfad
              wsim --sim verilator  rv32gc wally32a_lrsc
              wsim --sim verilator  rv32gc wally32priv
              wsim --sim verilator  rv32gc wally32periph
              wsim --sim verilator  rv32gc arch32zcb
              wsim --sim verilator  rv32gc arch32zbkb
              wsim --sim verilator  rv32gc arch32zbkc
              wsim --sim verilator  rv32gc arch32zbkx
              wsim --sim verilator  rv32gc arch32zknd
              wsim --sim verilator  rv32gc arch32zkne
              wsim --sim verilator  rv32gc arch32zknh
              wsim --sim verilator  rv64i arch64i
              wsim --sim verilator  rv64gc coverage64gc
              wsim --sim verilator  rv64gc arch64i
              wsim --sim verilator  rv64gc arch64priv
              wsim --sim verilator  rv64gc arch64c
              wsim --sim verilator  rv64gc arch64m
              wsim --sim verilator  rv64gc arch64zcb
              wsim --sim verilator  rv64gc arch64zifencei
              wsim --sim verilator  rv64gc arch64zicond
              wsim --sim verilator  rv64gc arch64a_amo
              wsim --sim verilator  rv64gc wally64a_lrsc
              wsim --sim verilator  rv64gc wally64periph
              wsim --sim verilator  rv64gc wally64priv
              wsim --sim verilator  rv64gc arch64zbkb
              wsim --sim verilator  rv64gc arch64zbkc
              wsim --sim verilator  rv64gc arch64zbkx
              wsim --sim verilator  rv64gc arch64zknd
              wsim --sim verilator  rv64gc arch64zkne
              wsim --sim verilator  rv64gc arch64zknh
              wsim --sim verilator  rv64gc arch64zba
              wsim --sim verilator  rv64gc arch64zbb
              wsim --sim verilator  rv64gc arch64zbc
              wsim --sim verilator  rv64gc arch64zbs
              wsim --sim verilator  rv64gc arch64f
              wsim --sim verilator  rv64gc arch64d
              wsim --sim verilator  rv64gc arch64zfh
              wsim --sim verilator  rv64gc arch64f_fma
              wsim --sim verilator  rv64gc arch64d_fma
              wsim --sim verilator  rv64gc arch64zfh_fma
              wsim --sim verilator  rv64gc arch64f_divsqrt
              wsim --sim verilator  rv64gc arch64d_divsqrt
              wsim --sim verilator  rv64gc arch64zfh_divsqrt
              wsim --sim verilator  rv64gc arch64zfaf
              wsim --sim verilator  rv64gc arch64zfad
