name: Installation

on: [workflow_dispatch]

jobs:
  ubuntu_install:
    name: Test installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
      - name: Free up storage
        run: |
              sudo rm -rf /usr/local/lib/android &> /dev/null
              sudo rm -rf /usr/share/dotnet &> /dev/null
              sudo rm -rf /opt/ghc &> /dev/null
              sudo rm -rf /opt/hostedtoolcache/CodeQL &> /dev/null
              sudo docker image prune --all --force &> /dev/null
              sudo apt-get purge -y \
                '^llvm-.*' \
                'php.*' \
                '^mongodb-.*' \
                '^mysql-.*' \
                azure-cli \
                google-cloud-cli \
                google-chrome-stable \
                firefox \
                powershell \
                microsoft-edge-stable \
                mono-devel \
                &> /dev/null
              sudo apt-get autoremove -y &> /dev/null
              sudo apt-get clean &> /dev/null
              df -h
      - uses: actions/checkout@v4
      - name: install
        run: sudo ./bin/wally-tool-chain-install.sh
  rhel_family_install:
    name: Test installation on ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
      options: --privileged --mount type=bind,source=/,target=/host
    strategy:
      fail-fast: false
      matrix:
        os: ["rockylinux:8", "almalinux:8"]
    steps:
      - name: check distro
        run: cat /etc/os-release
      - run: dnf install -y sudo
      - name: free up storage
        run: |
              df -h
              sudo rm -rf /host/usr/local/lib/android
              sudo rm -rf /host/usr/share/dotnet &> /dev/null
              sudo rm -rf /host/opt/ghc &> /dev/null
              sudo rm -rf /host/opt/hostedtoolcache/CodeQL &> /dev/null
              df -h
      - uses: actions/checkout@v4
      - name: install
        run: ./bin/wally-tool-chain-install.sh
