name: Installation test

on: [workflow_dispatch]

jobs:
  install:
    name: Test installation on Rocky 9
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash

    steps:
      - run: df -h
      - name: free up storage
        run: sudo rm -rf /usr/local/lib/android
      - run: docker start -ia rockylinux:8
      - run: dnf install -y sudo
      - uses: actions/checkout@v4
      - name: install
        run: ./bin/wally-tool-chain-install.sh
    
