name: Rocky installation test

on: [workflow_dispatch]

jobs:
  install:
    name: Test installation on Rocky 8
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
      options: --privileged --mount type=bind,source=/,target=/host
    steps:
      - name: check distro
        run: cat /etc/os-release
      - run: dnf install -y sudo
      - name: free up storage
        run: |
              df -h
              sudo rm -rf /host/usr/local/lib/android
              sudo rm -rf /host/usr/share/dotnet &> /dev/null
              sudo rm -rf /host/opt/ghc &> /dev/null
              sudo rm -rf /host/opt/hostedtoolcache/CodeQL &> /dev/null
              df -h
      - uses: actions/checkout@v4
      - name: install
        run: ./bin/wally-tool-chain-install.sh

