name: Installation test

on: [workflow_dispatch]

jobs:
  install:
    name: Test installation on Rocky 9
    runs-on: ubuntu-latest
    container: rockylinux:8
    defaults:
      run: 
        shell: bash

    steps:
      - run: df -h
      - uses: actions/checkout@v4
      - name: install
        run: ./bin/wally-tool-chain-install.sh
    
