name: List Storage Space
on: [workflow_dispatch]


jobs:
  check-packages:
    name: Test installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - name: check packages
        run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr

  
