on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: touch test.txt
      - run: |
          df -h
          ./.github/cli-space-cleanup.sh
          df -h
      - run: |
          sudo ls -l
          sudo du -h --max-depth=1
