name: Test

on: [workflow_dispatch]

jobs:
  ubuntu_install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Free up storage
        run: |
              df -h
              ./.github/cli-space-cleanup.sh
              df -h
      - run: mkdir -p /opt/riscv
      - run: sudo apt install -y python3 python3-pip python3-venv
      - run: python3 -m venv /opt/riscv
      - run: |
              source /opt/riscv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
      - name: make tests
        run: |
              source setup.sh
              source /opt/riscv/bin/activate
              make || true


  rhel_family_install:
    name: Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
      options: --privileged --mount type=bind,source=/,target=/host --pid=host --entrypoint /bin/bash
    strategy:
      fail-fast: false
      matrix:
        os: ["rockylinux:8", "rockylinux:9", "almalinux:8", "almalinux:9"]
    steps:
      - name: Install dependencies
        run: |
              dnf install -y sudo git
              dnf install curl -y --allowerasing || true
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: dnf install -y python3.12 python3-pip
      - run: mkdir -p /opt/riscv
      - run: python3.12 -m venv /opt/riscv
      - run: |
              source /opt/riscv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
      - name: make tests
        run: |
              source setup.sh
              source /opt/riscv/bin/activate
              make || true
      - name: regresssion
        run: |
              source setup.sh
              regression-wally
