name: Test
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  ubuntu_install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - uses: actions/checkout@v4
        # with:
        #   submodules: recursive
      - run: |
          df -h
          ./.github/cli-space-cleanup.sh
          df -h
      - run: sudo ./bin/wally-package-install.sh
